# Generated by Django 4.2.5 on 2024-07-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Title', max_length=32)),
                ('brief_content', models.CharField(max_length=256, null=True)),
                ('content', models.TextField(null=True)),
                ('publish_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
